import { invoke } from "@tauri-apps/api/core";
import type {
  AssistantBriefingApplyPayload,
  AssistantBriefingPayload,
  AssistantBriefingQueryInput,
  AssistantBriefingRecord,
  AssistantBriefingSuggestionRecord,
  AssistantBriefingTickPayload,
  DeadlineScanResult,
  FeishuBatchResult,
  FeishuInboundInput,
  FeishuRetryResult,
  FeishuWebhookResult,
  FeishuMessageLogQueryInput,
  FeishuMessageLogRecord,
  NewWebWatcherInput,
  NewWatchTargetInput,
  NotificationRecord,
  NotificationPriorityRebalanceResult,
  NotificationSuggestionBatchResult,
  SchedulerTickResult,
  FeishuCommandResult,
  MathNotebookResult,
  NotificationQueryInput,
  SuggestionApplyPayload,
  TaskSuggestion,
  WatchScanResult,
  WatchScanTickResult,
  WatchTarget,
  WebCaptureInput,
  WebCapturePayload,
  WebChangeLog,
  WebChangeLogQueryInput,
  WebClipping,
  WebPreset,
  WebSource,
  WebSourceLinkUpdateInput,
  WebSourceQueryInput,
  WebWatcher,
  WebWatcherQueryInput,
  WebWatcherScanPayload,
  WebWatcherScanTickPayload,
  WebhookServerStatus,
} from "@/features/integrations/types";

export async function getAppSetting(key: string) {
  return invoke<string | null>("get_app_setting", { key });
}

export async function setAppSetting(key: string, value: string) {
  return invoke<void>("set_app_setting", { key, value });
}

export async function runSecureAiPrompt(payload: {
  model?: string | null;
  systemPrompt?: string | null;
  prompt: string;
}) {
  return invoke<{
    text: string;
    provider: string;
    model: string;
    inputTokens: number | null;
    outputTokens: number | null;
  }>("run_secure_ai_prompt", {
    model: payload.model ?? null,
    systemPrompt: payload.systemPrompt ?? null,
    prompt: payload.prompt,
  });
}

export async function listNotifications(limit = 30) {
  return invoke<NotificationRecord[]>("list_notifications", { limit });
}

export async function listNotificationsWithFilters(payload: NotificationQueryInput) {
  return invoke<NotificationRecord[]>("list_notifications_with_filters", { payload });
}

export async function markNotificationRead(notificationId: number, isRead = true) {
  return invoke<void>("mark_notification_read", { notificationId, isRead });
}

export async function ignoreNotification(notificationId: number, reason?: string) {
  return invoke<void>("ignore_notification", { notificationId, reason: reason ?? null });
}

export async function snoozeNotification(notificationId: number, preset: "1h" | "later_today" | "tomorrow") {
  return invoke<string>("snooze_notification", { notificationId, preset });
}

export async function createTaskFromNotification(notificationId: number) {
  return invoke<number>("create_task_from_notification", { notificationId });
}

export async function logNotificationAction(
  notificationId: number,
  actionName: string,
  actionPayloadJson?: string | null,
) {
  return invoke<void>("log_notification_action", {
    notificationId,
    actionName,
    actionPayloadJson: actionPayloadJson ?? null,
  });
}

export async function sendFeishuTestMessage(content?: string) {
  return invoke<void>("send_feishu_test_message", { content: content ?? null });
}

export async function runDeadlineNotificationScan() {
  return invoke<DeadlineScanResult>("run_deadline_notification_scan");
}

export async function runScheduledNotificationTick() {
  return invoke<SchedulerTickResult>("run_scheduled_notification_tick");
}

export async function generateAssistantBriefing(briefType: "morning" | "evening", autoGenerated?: boolean) {
  return invoke<AssistantBriefingPayload>("generate_assistant_briefing", {
    briefType,
    autoGenerated: autoGenerated ?? null,
  });
}

export async function listAssistantBriefings(payload?: AssistantBriefingQueryInput) {
  return invoke<AssistantBriefingRecord[]>("list_assistant_briefings", { payload: payload ?? null });
}

export async function listAssistantBriefingSuggestions(briefingId: number) {
  return invoke<AssistantBriefingSuggestionRecord[]>("list_assistant_briefing_suggestions", { briefingId });
}

export async function applyAssistantBriefingSuggestion(suggestionId: number) {
  return invoke<AssistantBriefingApplyPayload>("apply_assistant_briefing_suggestion", { suggestionId });
}

export async function runAssistantBriefingTick() {
  return invoke<AssistantBriefingTickPayload>("run_assistant_briefing_tick");
}

export async function listWatchTargets() {
  return invoke<WatchTarget[]>("list_watch_targets");
}

export async function createWatchTarget(payload: NewWatchTargetInput) {
  return invoke<number>("create_watch_target", { payload });
}

export async function deleteWatchTarget(targetId: number) {
  return invoke<void>("delete_watch_target", { targetId });
}

export async function setWatchTargetActive(targetId: number, isActive: boolean) {
  return invoke<void>("set_watch_target_active", { targetId, isActive });
}

export async function runWatchTargetsScan() {
  return invoke<WatchScanResult>("run_watch_targets_scan");
}

export async function runWatchTargetsScanTick() {
  return invoke<WatchScanTickResult>("run_watch_targets_scan_tick");
}

export async function listWebPresets() {
  return invoke<WebPreset[]>("list_web_presets");
}

export async function listWebSources(payload?: WebSourceQueryInput) {
  return invoke<WebSource[]>("list_web_sources", { payload: payload ?? null });
}

export async function updateWebSourceLinks(payload: WebSourceLinkUpdateInput) {
  return invoke<void>("update_web_source_links", { payload });
}

export async function listWebWatchers(payload?: WebWatcherQueryInput) {
  return invoke<WebWatcher[]>("list_web_watchers", { payload: payload ?? null });
}

export async function listWebChangeLogs(payload?: WebChangeLogQueryInput) {
  return invoke<WebChangeLog[]>("list_web_change_logs", { payload: payload ?? null });
}

export async function listWebClippings(sourceId?: number | null, limit?: number | null) {
  return invoke<WebClipping[]>("list_web_clippings", {
    sourceId: sourceId ?? null,
    limit: limit ?? null,
  });
}

export async function createWebWatcher(payload: NewWebWatcherInput) {
  return invoke<number>("create_web_watcher", { payload });
}

export async function setWebWatcherActive(watcherId: number, isActive: boolean) {
  return invoke<void>("set_web_watcher_active", { watcherId, isActive });
}

export async function deleteWebWatcher(watcherId: number) {
  return invoke<void>("delete_web_watcher", { watcherId });
}

export async function captureWebUrl(payload: WebCaptureInput) {
  return invoke<WebCapturePayload>("capture_web_url", { payload });
}

export async function runWebWatchersScan(includeManual = false) {
  return invoke<WebWatcherScanPayload>("run_web_watchers_scan", { includeManual });
}

export async function runWebWatcherCheck(watcherId: number) {
  return invoke<WebWatcherScanPayload>("run_web_watcher_check", { watcherId });
}

export async function runWebWatchersScanTick() {
  return invoke<WebWatcherScanTickPayload>("run_web_watchers_scan_tick");
}

export async function createTaskFromWebChange(changeId: number) {
  return invoke<number>("create_task_from_web_change", { changeId });
}

export async function markWebChangeProcessed(changeId: number, processed: boolean) {
  return invoke<void>("mark_web_change_processed", { changeId, processed });
}

export async function listTaskSuggestions(status: string | null = "pending", limit = 50) {
  return invoke<TaskSuggestion[]>("list_task_suggestions", {
    status,
    limit,
  });
}

export async function applyTaskSuggestion(suggestionId: number) {
  return invoke<SuggestionApplyPayload>("apply_task_suggestion", { suggestionId });
}

export async function dismissTaskSuggestion(suggestionId: number) {
  return invoke<void>("dismiss_task_suggestion", { suggestionId });
}

export async function executeFeishuCommand(command: string) {
  return invoke<FeishuCommandResult>("execute_feishu_command", { command });
}

export async function executeFeishuCommandBatch(command: string) {
  return invoke<FeishuBatchResult>("execute_feishu_command_batch", { command });
}

export async function processFeishuInboundMessage(payload: FeishuInboundInput) {
  return invoke<FeishuCommandResult>("process_feishu_inbound_message", { payload });
}

export async function processFeishuWebhookPayload(rawJson: string) {
  return invoke<FeishuWebhookResult>("process_feishu_webhook_payload", { rawJson });
}

export async function startFeishuWebhookServer(port?: number) {
  return invoke<WebhookServerStatus>("start_feishu_webhook_server", { port: port ?? null });
}

export async function stopFeishuWebhookServer() {
  return invoke<WebhookServerStatus>("stop_feishu_webhook_server");
}

export async function getFeishuWebhookServerStatus() {
  return invoke<WebhookServerStatus>("get_feishu_webhook_server_status");
}

export async function listFeishuMessageLogs(payload?: FeishuMessageLogQueryInput) {
  return invoke<FeishuMessageLogRecord[]>("list_feishu_message_logs", { payload: payload ?? null });
}

export async function retryFailedFeishuMessages(limit?: number | null) {
  return invoke<FeishuRetryResult>("retry_failed_feishu_messages", { limit: limit ?? null });
}

export async function generateTaskSuggestionsFromNotifications(limit?: number | null) {
  return invoke<NotificationSuggestionBatchResult>("generate_task_suggestions_from_notifications", {
    limit: limit ?? null,
  });
}

export async function rebalanceTaskPriorityFromNotifications(limit?: number | null) {
  return invoke<NotificationPriorityRebalanceResult>("rebalance_task_priority_from_notifications", {
    limit: limit ?? null,
  });
}

export async function openExternalUrl(url: string) {
  return invoke<void>("open_external_url", { url });
}

export async function sendWebSessionMessage(payload: {
  provider: string;
  threadUrl: string;
  text: string;
}) {
  return invoke<string>("send_web_session_message", {
    payload: {
      provider: payload.provider,
      threadUrl: payload.threadUrl,
      text: payload.text,
    },
  });
}

export async function readWebSessionMessage(payload: {
  provider: string;
  threadUrl: string;
}) {
  return invoke<{
    provider: string;
    threadUrl: string;
    status: string;
    text: string;
  }>("read_web_session_message", {
    payload: {
      provider: payload.provider,
      threadUrl: payload.threadUrl,
    },
  });
}

export async function startMathErrorNotebook() {
  return invoke<MathNotebookResult>("start_math_error_notebook");
}

export async function openMathErrorNotebook() {
  return invoke<MathNotebookResult>("open_math_error_notebook");
}
